### PR TITLE
Fixes Issue145-Clicking Remove Song From Queue Plays the Song

### LINKED ISSUE #145: Clicking Remove Song From Queue Plays the Song
I noticed that in the queue list view, if I click on remove song from the queue, this would removed the song but however also triggers the song to play, this would create a unpleasant user experience since they would need to manually stop the song.

### PR DESCRIPTION
**Pull request by Wei-J-Huang**
Fixes #145 

I have updated the code to prevent clicking "remove song from queue icon" to play the song that is about to be removed. Also while I was at it, I noticed that the event handler name ```onClickImage``` was used to play the song, since this is a list view, there is no image to click on, I have changed the name of the handler to ```onClickMusicRow``` instead. Let me know what you think.

### CODE REVIEW

**Comment by unjown** [comment]
@Wei-J-Huang how did u find this project?

**Comment by Wei-J-Huang** [comment]
@unjown I am a college student, enrolled in an open source course this semester. I've worked on two issues on this project few weeks ago when it was called Artistify for my assignment and found this project interesting, so I've decided to revisit this :)

**Comment by unjown** [comment]
> @unjown I am a college student, enrolled in an open source course this semester. I've worked on two issues on this project few weeks ago when it was called Artistify for my assignment and found this project interesting, so I've decided to revisit this :)

nice

**Comment by unjown** [comment]
join our discord :) im waiting for approval to merge from admin

**Review by IanWalston — APPROVED** [review]
looks good to me, thanks!

**Pull request merged**
